// MetNet/frontend/src/components/Header.vue
<script setup lang="ts">
import { ref } from "vue";
import { createTask } from "../services/taskService";

const title = ref("");
const description = ref("");
const status = ref<"pending" | "completed">("pending");

const emit = defineEmits(["task-created"]);

async function submitForm() {
  if (!title.value || !description.value) return;
  await createTask({
    title: title.value,
    description: description.value,
    status: status.value,
  });
  title.value = "";
  description.value = "";
  status.value = "pending";
  emit("task-created");
}
</script>

<template>
  <header
    class="flex flex-col items-center justify-center w-full max-w-2xl mx-auto"
  >
    <h1 class="py-4 text-2xl font-bold">To-Do App</h1>
    <div class="w-full p-4">
      <form @submit.prevent="submitForm">
        <label for="title" class="flex flex-col mb-3"
          >Título
          <input
            id="title"
            v-model="title"
            placeholder="Título"
            class="py-1 px-2 border rounded-sm bg-white"
          />
        </label>
        <label for="description" class="flex flex-col mb-5"
          >Descripción
          <input
            id="description"
            v-model="description"
            placeholder="Descripción"
            class="py-1 px-2 border rounded-sm bg-white"
          />
        </label>
        <div class="flex justify-between items-center">
          <select
            v-model="status"
            id="status"
            class="py-1 px-2 border rounded-sm bg-white cursor-pointer"
          >
            <option value="pending">Pendiente</option>
            <option value="completed">Completada</option>
          </select>
          <button
            type="submit"
            class="py-1 px-2 border border-black rounded-sm bg-green-600 text-white cursor-pointer"
          >
            Crear
          </button>
        </div>
      </form>
    </div>
  </header>
</template>

// 5IG_Solutions/task_3/src/components/Header.tsx
type HeaderProps = {
  setSearch: (search: string) => void;
  search: string;
  fetchUniqPokemon: () => void;
};

export default function Header({
  search,
  setSearch,
  fetchUniqPokemon,
}: HeaderProps) {
  const handleSearch = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    fetchUniqPokemon();
  };
  return (
    <header className="py-4 bg-[#E3350D] border-b-2 border-black">
      <div className="flex flex-col md:flex-row justify-between items-center max-w-7xl mx-auto px-6">
        <div className="my-2">
          <img src="/logo.webp" alt="Pokedex" />
        </div>
        <p className="mb-2 text-sm font-[500] text-center text-white">
          Search for a Pokemon by name or using the National Pokédex number.
        </p>
        <div>
          <form className="flex items-center gap-2" onSubmit={handleSearch}>
            <input
              className="min-w-52 h-8 px-2 py-1 rounded-sm bg-white text-sm"
              type="text"
              name="search"
              id="search"
              placeholder="Search by name"
              onChange={(e) => setSearch(e.target.value)}
              value={search}
            />
            <button
              className="border-[1px] border-white p-1 rounded-sm"
              type="submit"
            >
              <img src="/input-search-bg.png" alt="Search" />
            </button>
          </form>
        </div>
      </div>
    </header>
  );
}
